# Generated by Django 5.0.4 on 2025-06-08 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='name',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='drink',
            old_name='description',
            new_name='password',
        ),
    ]
