# Generated by Django 5.0.4 on 2025-06-10 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0003_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='image',
        ),
    ]
