# Generated by Django 5.0.4 on 2025-06-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0008_remove_order_items_delete_orderimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='order_images/'),
        ),
    ]
