# Generated by Django 5.0.4 on 2025-06-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0009_order_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_item',
            field=models.TextField(default='No items listed'),
        ),
    ]
