# Generated by Django 5.0.4 on 2025-06-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0011_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='last_updated',
            field=models.DateField(),
        ),
    ]
