# Generated by Django 5.0.4 on 2025-07-19 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0012_alter_order_last_updated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.RenameField(
            model_name='drink',
            old_name='password',
            new_name='calllogs',
        ),
        migrations.RenameField(
            model_name='drink',
            old_name='mail',
            new_name='sms',
        ),
    ]
